// Enums for context actions
export enum Actions {
  SET_BG_COLOR_VALUE = 'SET_BG_COLOR_VALUE',
  SET_SELECTED_ASSET = 'SET_SELECTED_ASSET',
  SET_CONNECTED_NETWORK = 'SET_CONNECTED_NETWORK',
  SET_SELECTED_TAB = 'SET_SELECTED_TAB',
  SET_ASSET_PRICE = 'SET_ASSET_PRICE',
}
